### URL base da sua API
@baseUrl = http://192.168.39.60:30000/api/v1

### Variável para armazenar o token JWT e o ID do usuário
@token =
@userId =

### 1. Registrar um novo usuário
POST {{baseUrl}}/users
Content-Type: application/json

{
    "email": "testuser@example.com",
    "password": "password123",
    "firstName": "User",
    "lastName": "Test"
}

### 2. Login de um usuário
# Este endpoint irá retornar um token JWT
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "testuser@example.com",
    "password": "password123"
}

### 3. Obter a lista de todos os usuários
# Certifique-se de que a requisição de registro acima foi bem sucedida
# GET {{baseUrl}}/users
# Authorization: Bearer {{token}}

### 4. Obter o perfil de um usuário específico
# Substitua o ID na URL para o ID do usuário que você registrou
GET {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{token}}

### 5. Atualizar os dados de um usuário
# Substitua o ID na URL para o ID do usuário que você deseja atualizar
# Altere os dados no corpo da requisição conforme necessário
PUT {{baseUrl}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "firstName": "Usuario",
    "lastName": "Atualizado"
}

### 6. Deletar um usuário
# Substitua o ID na URL para o ID do usuário que você deseja deletar
DELETE {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{token}}
